export const userActionConstants = {
  SET_GUEST: "SET_GUEST",
  SAVE_GUEST: "SAVE_GUEST",
  SET_ADMIN: "SET_ADMIN"
};

export const screenActionConsants = {
  POWER_OFF: "POWER_OFF",
  POWER_ON: "POWER_ON",
  SCREEN_LOADED: "SCREEN_LOADED",
  SCREEN_UNLOADED: "SCREEN_UNLOADED",
  SET_GREETING: "SET_GREETING",
  CLEAR_GREETING: "CLEAR_GREETING"
};